steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/sep4-cloud-386107/restapi:latest', '-f', './Rest.Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/sep4-cloud-386107/websocket:latest', '-f', './WebSocket.Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', './k8s/deployment.yml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=reptimate-cluster'

images:
  - 'eu.gcr.io/sep4-cloud-386107/restapi:latest'
  - 'eu.gcr.io/sep4-cloud-386107/websocket:latest'
