steps:
  # Build and push WebSocket Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/sep4-cloud-386107/websocket:latest', '-f', 'WebSocket.Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/sep4-cloud-386107/websocket:latest']

  # Build and push RestAPI Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/sep4-cloud-386107/restapi:latest', '-f', 'Rest.Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/sep4-cloud-386107/restapi:latest']

  # Prepare deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/deployment.yml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=reptimate-cluster'

  # Save Kubernetes configs
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: ['save', '--cluster=reptimate-cluster', '--region=europe-west1', '--project=sep4-cloud-386107']
    dir: '/workspace'

  # Apply deployment
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: ['apply', '--filename=k8s/deployment.yml', '--cluster=reptimate-cluster', '--region=europe-west1', '--project=sep4-cloud-386107']
    dir: '/workspace'

images:
  - 'eu.gcr.io/sep4-cloud-386107/websocket:latest'
  - 'eu.gcr.io/sep4-cloud-386107/restapi:latest'
