name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Install EF Core
        run: dotnet tool install --global dotnet-ef
        
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: sep4-cloud-386107
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Connect to Cloud SQL
        run: |
          gcloud sql connect reptimate --user=${{ secrets.DB_USER }} --quiet

      - name: Build
        run: dotnet build --configuration Release
        
      - name: Check migrations
        run: dotnet ef database update --project ./Repository --configuration Release --no-build  
        

  test:
    needs: build
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --configuration Release
