name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Download JDBC Driver
        run: |
          wget -q https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar -O mysql-connector-java.jar

      - name: Install EF Core
        run: dotnet tool install --global dotnet-ef
        
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: sep4-cloud-386107
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build
        run: dotnet build --configuration Release

      - name: Connect to Database
        run: |
          dotnet ef dbcontext scaffold --project ./Repository --configuration Release --no-build "Server=${{ env.DB_HOST }};Port=${{ env.DB_PORT }};Database=${{ env.DB_NAME }};Uid=${{ env.DB_USER }};Pwd=${{ env.DB_PASS }}" "Pomelo.EntityFrameworkCore.MySql" -o ./Repository/Entities -c MyDbContext
        
      - name: Check migrations
        run: dotnet ef database update --project ./Repository --configuration Release --no-build

      - name: Stop Cloud SQL Proxy
        run: |
          pkill cloud_sql_proxy

  test:
    needs: build
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --configuration Release
