name: Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: sep4-cloud-386107
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker eu.gcr.io
          docker build -t eu.gcr.io/sep4-cloud-386107/reptimate .
          docker push eu.gcr.io/sep4-cloud-386107/reptimate

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials reptimate-cluster --region europe-west1

      - name: Deploy to Kubernetes cluster
        run: |
          kubectl apply -f ../../k8s/deployment.yml